-- Create the whitelist table
create table public.whitelist (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  wallet_address text not null unique,
  has_followed_x boolean default false,
  has_joined_tg boolean default false
);

-- Set up Row Level Security (RLS)
alter table public.whitelist enable row level security;

-- Allow public access to insert data (since it's a public whitelist form)
create policy "Enable insert for public" on public.whitelist 
  for insert 
  with check (true);

-- Optional: If you want to prevent duplicate wallet addresses at the database level (already handled by unique constraint, but good for RLS if needed)
-- The unique constraint on wallet_address is sufficient for data integrity.
